export const mockData = [
	{
		userId: '1',
		username: 'Blackmore',
		fullName: 'Ritchie Blackmore',
		email: 'Blackmore@gmail.com',
		following: ['2'],
		followers: ['2', '3'],
		dataCreated: Date.now(),
	},
	{
		userId: '2',
		username: 'Lord',
		fullName: 'Jon Lord',
		email: 'Lord@gmail.com',
		following: ['1'],
		followers: ['1', '3', '4'],
		dataCreated: Date.now(),
	},
	{
		userId: '3',
		username: 'Paice',
		fullName: 'Ian Paice',
		email: 'Paice@gmail.com',
		following: ['1', '2', '4', '5'],
		followers: ['1', '2', '4', '5'],
		dataCreated: Date.now(),
	},
	{
		userId: '4',
		username: 'Gillan',
		fullName: 'Ian Gillan',
		email: 'Gillan@gmail.com',
		following: ['2', '3', '5'],
		followers: ['2', '5'],
		dataCreated: Date.now(),
	},
	{
		userId: '5',
		username: 'Glover',
		fullName: 'Roger Glover',
		email: 'Glover@gmail.com',
		following: ['3', '4'],
		followers: ['1', '2', '3', '4'],
		dataCreated: Date.now(),
	},
];
